spring.application.name=observability-demo
# Data Source Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/observability
spring.datasource.username=postgres
spring.datasource.password=2108

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Configuration
server.port=8082